/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ussemble;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author ACER
 */
public class addNewSetPage extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public addNewSetPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jOptionPane2 = new javax.swing.JOptionPane();
        backgroundPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        overviewBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        flashcardsBtn = new javax.swing.JButton();
        studyBtn = new javax.swing.JButton();
        profileIcon = new javax.swing.JButton();
        flashcardsIcon = new javax.swing.JButton();
        overviewIcon = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        profileBtn = new javax.swing.JButton();
        logOutIcon = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        logOutIcon1 = new javax.swing.JButton();
        addNewSetPanel = new javax.swing.JPanel();
        displayDeckTitle = new javax.swing.JTextField();
        displayAnswer = new javax.swing.JTextField();
        displayQuestion = new javax.swing.JTextField();
        nextCardBtn1 = new javax.swing.JButton();
        nextCardBtn2 = new javax.swing.JButton();
        nextCardBtn3 = new javax.swing.JButton();
        nextCardBtn5 = new javax.swing.JButton();
        displayDifficulty = new javax.swing.JTextField();
        addNewSetHeaderPanel = new javax.swing.JPanel();
        addNewSetLabel = new javax.swing.JTextField();
        backFlashcardsBtn = new javax.swing.JButton();
        finishSetBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        DiscardBTn = new javax.swing.JButton();
        nextCardBtn4 = new javax.swing.JButton();
        nextCardBtn = new javax.swing.JButton();
        saveCardBTn1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setForeground(new java.awt.Color(0, 55, 158));
        backgroundPanel.setMaximumSize(new java.awt.Dimension(960, 540));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(960, 540));

        sidebarPanel.setBackground(new java.awt.Color(229, 238, 255));

        overviewBtn.setBackground(new java.awt.Color(229, 238, 255));
        overviewBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        overviewBtn.setForeground(new java.awt.Color(0, 55, 158));
        overviewBtn.setText("Overview");
        overviewBtn.setBorder(null);
        overviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa new logo final.png"))); // NOI18N

        flashcardsBtn.setBackground(new java.awt.Color(0, 55, 158));
        flashcardsBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        flashcardsBtn.setForeground(new java.awt.Color(229, 238, 255));
        flashcardsBtn.setText("Flashcards");
        flashcardsBtn.setBorder(null);
        flashcardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flashcardsBtnActionPerformed(evt);
            }
        });

        studyBtn.setBackground(new java.awt.Color(229, 238, 255));
        studyBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        studyBtn.setForeground(new java.awt.Color(0, 55, 158));
        studyBtn.setText("Study");
        studyBtn.setBorder(null);
        studyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyBtnActionPerformed(evt);
            }
        });

        profileIcon.setBackground(new java.awt.Color(255, 255, 204));
        profileIcon.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        profileIcon.setForeground(new java.awt.Color(0, 55, 158));
        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studyIcon.png"))); // NOI18N
        profileIcon.setBorder(null);
        profileIcon.setBorderPainted(false);
        profileIcon.setContentAreaFilled(false);
        profileIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileIconActionPerformed(evt);
            }
        });

        flashcardsIcon.setBackground(new java.awt.Color(255, 255, 204));
        flashcardsIcon.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        flashcardsIcon.setForeground(new java.awt.Color(0, 55, 158));
        flashcardsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa flashcards.png"))); // NOI18N
        flashcardsIcon.setBorder(null);
        flashcardsIcon.setBorderPainted(false);
        flashcardsIcon.setContentAreaFilled(false);
        flashcardsIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flashcardsIconActionPerformed(evt);
            }
        });

        overviewIcon.setBackground(new java.awt.Color(255, 255, 204));
        overviewIcon.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        overviewIcon.setForeground(new java.awt.Color(0, 55, 158));
        overviewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeIcon.png"))); // NOI18N
        overviewIcon.setBorder(null);
        overviewIcon.setBorderPainted(false);
        overviewIcon.setContentAreaFilled(false);
        overviewIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewIconActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 55, 158));

        profileBtn.setBackground(new java.awt.Color(229, 238, 255));
        profileBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(0, 55, 158));
        profileBtn.setText("Profile");
        profileBtn.setBorder(null);
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        logOutIcon.setBackground(new java.awt.Color(255, 255, 204));
        logOutIcon.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        logOutIcon.setForeground(new java.awt.Color(0, 55, 158));
        logOutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa profile.png"))); // NOI18N
        logOutIcon.setBorder(null);
        logOutIcon.setBorderPainted(false);
        logOutIcon.setContentAreaFilled(false);
        logOutIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutIconActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(229, 238, 255));
        logOutBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(0, 55, 158));
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        logOutIcon1.setBackground(new java.awt.Color(255, 255, 204));
        logOutIcon1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        logOutIcon1.setForeground(new java.awt.Color(0, 55, 158));
        logOutIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa log out button.png"))); // NOI18N
        logOutIcon1.setBorder(null);
        logOutIcon1.setBorderPainted(false);
        logOutIcon1.setContentAreaFilled(false);
        logOutIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutIcon1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(flashcardsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(profileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(logOutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(logOutIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(overviewIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(flashcardsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                        .addComponent(overviewBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(studyBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)))
                .addGap(30, 30, 30))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flashcardsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flashcardsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(logOutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logOutIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        addNewSetPanel.setBackground(new java.awt.Color(255, 255, 255));

        displayDeckTitle.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        displayDeckTitle.setForeground(new java.awt.Color(0, 55, 158));
        displayDeckTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDeckTitleActionPerformed(evt);
            }
        });

        displayAnswer.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        displayAnswer.setForeground(new java.awt.Color(0, 55, 158));

        displayQuestion.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        displayQuestion.setForeground(new java.awt.Color(0, 55, 158));
        displayQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayQuestionActionPerformed(evt);
            }
        });

        nextCardBtn1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nextCardBtn1.setForeground(new java.awt.Color(0, 55, 158));
        nextCardBtn1.setText("Deck Title");
        nextCardBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nextCardBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCardBtn1ActionPerformed(evt);
            }
        });

        nextCardBtn2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nextCardBtn2.setForeground(new java.awt.Color(0, 55, 158));
        nextCardBtn2.setText("Question");
        nextCardBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nextCardBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCardBtn2ActionPerformed(evt);
            }
        });

        nextCardBtn3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nextCardBtn3.setForeground(new java.awt.Color(0, 55, 158));
        nextCardBtn3.setText("Answer");
        nextCardBtn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nextCardBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCardBtn3ActionPerformed(evt);
            }
        });

        nextCardBtn5.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nextCardBtn5.setForeground(new java.awt.Color(0, 55, 158));
        nextCardBtn5.setText("Difficulty");
        nextCardBtn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nextCardBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCardBtn5ActionPerformed(evt);
            }
        });

        displayDifficulty.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        displayDifficulty.setForeground(new java.awt.Color(0, 55, 158));
        displayDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDifficultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewSetPanelLayout = new javax.swing.GroupLayout(addNewSetPanel);
        addNewSetPanel.setLayout(addNewSetPanelLayout);
        addNewSetPanelLayout.setHorizontalGroup(
            addNewSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewSetPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addNewSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextCardBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextCardBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextCardBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextCardBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayAnswer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(displayQuestion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayDeckTitle)
                    .addComponent(displayDifficulty, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        addNewSetPanelLayout.setVerticalGroup(
            addNewSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewSetPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(addNewSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextCardBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayDeckTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addNewSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextCardBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(displayQuestion))
                .addGap(12, 12, 12)
                .addGroup(addNewSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextCardBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(addNewSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextCardBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        displayDeckTitle.setEnabled(false);
        displayDifficulty.setEnabled(false);
        nextCardBtn2.setEnabled(false);
        nextCardBtn3.setEnabled(false);

        addNewSetHeaderPanel.setBackground(new java.awt.Color(255, 255, 255));

        addNewSetLabel.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        addNewSetLabel.setForeground(new java.awt.Color(0, 55, 158));
        addNewSetLabel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addNewSetLabel.setText("Add New Set");
        addNewSetLabel.setBorder(null);
        addNewSetLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewSetLabelActionPerformed(evt);
            }
        });

        backFlashcardsBtn.setBackground(new java.awt.Color(229, 238, 255));
        backFlashcardsBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        backFlashcardsBtn.setForeground(new java.awt.Color(0, 55, 158));
        backFlashcardsBtn.setText("Back to Flashcards");
        backFlashcardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFlashcardsBtnActionPerformed(evt);
            }
        });

        finishSetBtn.setBackground(new java.awt.Color(0, 55, 158));
        finishSetBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        finishSetBtn.setForeground(new java.awt.Color(229, 238, 255));
        finishSetBtn.setText("Finish Set");
        finishSetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishSetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewSetHeaderPanelLayout = new javax.swing.GroupLayout(addNewSetHeaderPanel);
        addNewSetHeaderPanel.setLayout(addNewSetHeaderPanelLayout);
        addNewSetHeaderPanelLayout.setHorizontalGroup(
            addNewSetHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewSetHeaderPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(addNewSetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(backFlashcardsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishSetBtn)
                .addGap(60, 60, 60))
        );
        addNewSetHeaderPanelLayout.setVerticalGroup(
            addNewSetHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewSetHeaderPanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(addNewSetHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewSetLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewSetHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(finishSetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backFlashcardsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DiscardBTn.setBackground(new java.awt.Color(229, 238, 255));
        DiscardBTn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        DiscardBTn.setForeground(new java.awt.Color(0, 55, 158));
        DiscardBTn.setText("Discard Card");
        DiscardBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardBTnActionPerformed(evt);
            }
        });

        nextCardBtn4.setBackground(new java.awt.Color(255, 255, 204));
        nextCardBtn4.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nextCardBtn4.setForeground(new java.awt.Color(0, 55, 158));
        nextCardBtn4.setText("Previous Card");
        nextCardBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCardBtn4ActionPerformed(evt);
            }
        });

        nextCardBtn.setBackground(new java.awt.Color(255, 255, 204));
        nextCardBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nextCardBtn.setForeground(new java.awt.Color(0, 55, 158));
        nextCardBtn.setText("Next Card");
        nextCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCardBtnActionPerformed(evt);
            }
        });

        saveCardBTn1.setBackground(new java.awt.Color(229, 238, 255));
        saveCardBTn1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        saveCardBTn1.setForeground(new java.awt.Color(0, 55, 158));
        saveCardBTn1.setText("Save Card");
        saveCardBTn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCardBTn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DiscardBTn, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextCardBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextCardBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveCardBTn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiscardBTn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCardBTn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextCardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextCardBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addNewSetHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addNewSetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewSetHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewSetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarPanel.getAccessibleContext().setAccessibleName("sideBar");
        addNewSetPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, 966, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        backgroundPanel.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void overviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewBtnActionPerformed
        // TODO add your handling code here:
        OverviewPage overview = new OverviewPage();
        overview.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_overviewBtnActionPerformed

    private void flashcardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flashcardsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flashcardsBtnActionPerformed

    private void studyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyBtnActionPerformed
        // TODO add your handling code here:
        studySetPage study = new studySetPage();
        study.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_studyBtnActionPerformed

    private void profileIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileIconActionPerformed

    private void flashcardsIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flashcardsIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flashcardsIconActionPerformed

    private void overviewIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overviewIconActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        ProfilePage profile = new ProfilePage();
        profile.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_profileBtnActionPerformed

    private void logOutIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutIconActionPerformed

    private void displayDeckTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDeckTitleActionPerformed
        displayDeckTitle.setEnabled(false);// Disables the field (no clicking or editing)
    }//GEN-LAST:event_displayDeckTitleActionPerformed

    private void displayQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayQuestionActionPerformed

    private void DiscardBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardBTnActionPerformed

    
    }//GEN-LAST:event_DiscardBTnActionPerformed

    private void nextCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextCardBtnActionPerformed

    private void nextCardBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCardBtn1ActionPerformed
    String userInput = jOptionPane2.showInputDialog(this, "Enter your deck title:", "Input Dialog", jOptionPane2.QUESTION_MESSAGE);

    // Check if the user clicked 'Cancel' (userInput will be null) or entered a text
    if (userInput != null && !userInput.trim().isEmpty()) {
        // Set the user input as the text of displayDeckTitle (assuming it's a JTextField)
        displayDeckTitle.setText(userInput);
    } else {
        // Handle the case when the user cancels or doesn't enter anything
        System.out.println("User canceled the input or entered empty text.");
    }
    }//GEN-LAST:event_nextCardBtn1ActionPerformed

    private void nextCardBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCardBtn2ActionPerformed
    String userInput = jOptionPane2.showInputDialog(this, "Enter Question:", "Input Dialog", jOptionPane2.QUESTION_MESSAGE);

    // Check if the user clicked 'Cancel' (userInput will be null) or entered a text
    if (userInput != null && !userInput.trim().isEmpty()) {
        // Set the user input as the text of displayDeckTitle (assuming it's a JTextField)
        displayQuestion.setText(userInput);
    } else {
        // Handle the case when the user cancels or doesn't enter anything
        System.out.println("User canceled the input or entered empty text.");
    }
    }//GEN-LAST:event_nextCardBtn2ActionPerformed

    private void nextCardBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCardBtn3ActionPerformed
    String userInput = jOptionPane2.showInputDialog(this, "Enter Answer:", "Input Dialog", jOptionPane2.QUESTION_MESSAGE);

    // Check if the user clicked 'Cancel' (userInput will be null) or entered a text
    if (userInput != null && !userInput.trim().isEmpty()) {
        // Set the user input as the text of displayDeckTitle (assuming it's a JTextField)
        displayAnswer.setText(userInput);
    } else {
        // Handle the case when the user cancels or doesn't enter anything
        System.out.println("User canceled the input or entered empty text.");
    }
    }//GEN-LAST:event_nextCardBtn3ActionPerformed

    private void saveCardBTn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCardBTn1ActionPerformed
    // Get the text from the JTextFields
    String difficulty = displayDifficulty.getText();
    String question = displayQuestion.getText();
    String answer = displayAnswer.getText();
    
    // Define the file name or path where you want to save the data
    String fileName = "saved_cards.txt";  // You can change the file path and name as needed
    
    try {
        // Create a FileWriter to write to the file (true to append)
        FileWriter writer = new FileWriter(fileName, true); // 'true' means append to the file
        
        
        // Write the data to the file in a simple format
        writer.write("Difficulty: " + difficulty + "\n");
        writer.write("Question: " + question + "\n");
        writer.write("Answer: " + answer + "\n");
        writer.write("-------------------------\n");  // Separator between entries
        
        // Close the writer
        writer.close();
        
        // Optionally, show a message to confirm the data was saved
        jOptionPane2.showMessageDialog(null, "Card saved successfully!");
        
        // Step to clear the text fields after saving
        displayQuestion.setText("");  // Clear the question field
        displayAnswer.setText("");    // Clear the answer field
        displayDifficulty.setText("");
        
    } catch (IOException e) {
        // Handle any errors that occur during file writing
        jOptionPane2.showMessageDialog(null, "Error saving card: " + e.getMessage());
    }
    }//GEN-LAST:event_saveCardBTn1ActionPerformed

    
    
    private void backFlashcardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFlashcardsBtnActionPerformed
        // TODO add your handling code here:
        FlashcardsPage flashcard = new FlashcardsPage();
        flashcard.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backFlashcardsBtnActionPerformed

    
    private void finishSetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishSetBtnActionPerformed
    try {
    // Read the existing content from saved_cards.txt
    File file = new File("saved_cards.txt");
    BufferedReader reader = new BufferedReader(new FileReader(file));
    
    StringBuilder fileContent = new StringBuilder();
    String line;
    while ((line = reader.readLine()) != null) {
        fileContent.append(line).append("\n");
    }
    reader.close();

    // Get the deck title from the JTextField
    String deckTitle = displayDeckTitle.getText().trim();

    // Ensure the deckTitle is not empty
    if (!deckTitle.isEmpty()) {
        // Get the username from OverviewPage using its public setter/getter
        OverviewPage overviewPage = new OverviewPage(); // Assuming you need to create a new instance
        String username = overviewPage.getDisplayUsername().trim(); // Use the getter method

        // Create the Flashcards folder if it doesn't exist
        File flashcardsFolder = new File("Flashcards");
        if (!flashcardsFolder.exists()) {
            flashcardsFolder.mkdir();
        }

        // Create a folder with the username inside Flashcards
        File userFolder = new File(flashcardsFolder, username);
        if (!userFolder.exists()) {
            userFolder.mkdir();
        }

        // Create the new file in the user's folder
        File newFile = new File(userFolder, deckTitle + ".txt");
        BufferedWriter writer = new BufferedWriter(new FileWriter(newFile));

        // Write the content from saved_cards.txt into the new file
        writer.write(fileContent.toString());
        writer.close();

        // Clear the content of saved_cards.txt
        BufferedWriter fileWriter = new BufferedWriter(new FileWriter(file));
        fileWriter.write(""); // Write an empty string to clear the file
        fileWriter.close();

        // Clear the JTextField after saving
        displayDeckTitle.setText("");

        // Success message
        jOptionPane2.showMessageDialog(null, "Deck saved in " + newFile.getAbsolutePath());
    } else {
        // If the deck title is empty, show a warning
        jOptionPane2.showMessageDialog(null, "Please enter a valid deck title.");
    }

    // Clear the question and answer fields
    displayQuestion.setText(""); // Clear the question field
    displayAnswer.setText("");   // Clear the answer field

} catch (IOException e) {
    // Handle IO exceptions
    jOptionPane2.showMessageDialog(null, "Error reading or writing the file: " + e.getMessage());
}
    }//GEN-LAST:event_finishSetBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
    // Show a confirmation dialog
    int choice = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Confirm LogOut?", 
        "Log Out", 
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        // Redirect to the login page
        Login loginPage = new Login();
        loginPage.setVisible(true);
        this.dispose(); // Close the current window
    } else {
        // Do nothing; close the dialog automatically
        System.out.println("Log out canceled.");
    }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void logOutIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutIcon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutIcon1ActionPerformed

    private void addNewSetLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewSetLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewSetLabelActionPerformed

    private void nextCardBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCardBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextCardBtn4ActionPerformed

    private void nextCardBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCardBtn5ActionPerformed
    // Define the options for the dialog
    String[] options = {"Easy", "Moderate", "Difficult"};
    
    // Show the option dialog and capture the user's choice
    int choice = jOptionPane2.showOptionDialog(
        this, // Parent component
        "Select the difficulty level:", // Message
        "Set Difficulty", // Title
        jOptionPane2.DEFAULT_OPTION, // Option type
        jOptionPane2.INFORMATION_MESSAGE, // Message type
        null, // Icon (null for default)
        options, // Options array
        options[0] // Default option
    );
    
    // Check the user's choice and set the text in displayDifficulty JTextField
    if (choice == 0) { // Easy selected
        displayDifficulty.setText("Easy");
    } else if (choice == 1) { // Moderate selected
        displayDifficulty.setText("Moderate");
    } else if (choice == 2) { // Difficult selected
        displayDifficulty.setText("Difficult");
    }
    
    }//GEN-LAST:event_nextCardBtn5ActionPerformed

    private void displayDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDifficultyActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_displayDifficultyActionPerformed

    private void saveToFile(String data) throws IOException {
    // Define the file name or path where you want to save the data
    String fileName = "saved_cards.txt";  // You can change the file path and name as needed

    // Create a FileWriter to write to the file (true to append)
    FileWriter writer = new FileWriter(fileName, true); // 'true' means append to the file
    
    // Write the data to the file in a simple format
    writer.write(data + "\n"); // Write each entry on a new line
    writer.write("-------------------------\n");  // Separator between entries

    // Close the writer
    writer.close();
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewSetPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewSetPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewSetPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewSetPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewSetPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DiscardBTn;
    private javax.swing.JPanel addNewSetHeaderPanel;
    private javax.swing.JTextField addNewSetLabel;
    private javax.swing.JPanel addNewSetPanel;
    private javax.swing.JButton backFlashcardsBtn;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField displayAnswer;
    private javax.swing.JTextField displayDeckTitle;
    private javax.swing.JTextField displayDifficulty;
    private javax.swing.JTextField displayQuestion;
    private javax.swing.JButton finishSetBtn;
    private javax.swing.JButton flashcardsBtn;
    private javax.swing.JButton flashcardsIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton logOutIcon;
    private javax.swing.JButton logOutIcon1;
    private javax.swing.JButton nextCardBtn;
    private javax.swing.JButton nextCardBtn1;
    private javax.swing.JButton nextCardBtn2;
    private javax.swing.JButton nextCardBtn3;
    private javax.swing.JButton nextCardBtn4;
    private javax.swing.JButton nextCardBtn5;
    private javax.swing.JButton overviewBtn;
    private javax.swing.JButton overviewIcon;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton profileIcon;
    private javax.swing.JButton saveCardBTn1;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton studyBtn;
    // End of variables declaration//GEN-END:variables
}
