/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ussemble;

import java.io.File;

/**
 *
 * @author ACER
 */

public class OverviewPage extends javax.swing.JFrame {
    /**
     * Creates new form 
     */
    public OverviewPage() {
        initComponents();
        displayUsername.setText(Login.currentUsername);
        displayNumberOfSets();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        overviewBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        flashcardsBtn = new javax.swing.JButton();
        studyBtn = new javax.swing.JButton();
        profileIcon = new javax.swing.JButton();
        flashcardsIcon = new javax.swing.JButton();
        overviewIcon = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        profileBtn = new javax.swing.JButton();
        logOutIcon = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        flashcardsIcon1 = new javax.swing.JButton();
        numCardsPanel = new javax.swing.JPanel();
        setOfCardsLabel = new javax.swing.JLabel();
        displayNumSets1 = new javax.swing.JTextField();
        setIcon = new javax.swing.JLabel();
        headerOverviewPanel = new javax.swing.JPanel();
        displayUsername = new javax.swing.JTextField();
        displayStatus = new javax.swing.JTextField();
        headerprofileIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        starIcon = new javax.swing.JLabel();
        displayDayStreak = new javax.swing.JTextField();
        dayStreakLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setForeground(new java.awt.Color(0, 55, 158));
        backgroundPanel.setMaximumSize(new java.awt.Dimension(960, 540));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(960, 540));

        sidebarPanel.setBackground(new java.awt.Color(229, 238, 255));

        overviewBtn.setBackground(new java.awt.Color(0, 55, 158));
        overviewBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        overviewBtn.setForeground(new java.awt.Color(229, 238, 255));
        overviewBtn.setText("Overview");
        overviewBtn.setBorder(null);
        overviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa new logo final.png"))); // NOI18N

        flashcardsBtn.setBackground(new java.awt.Color(229, 238, 255));
        flashcardsBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        flashcardsBtn.setForeground(new java.awt.Color(0, 55, 158));
        flashcardsBtn.setText("Flashcards");
        flashcardsBtn.setBorder(null);
        flashcardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flashcardsBtnActionPerformed(evt);
            }
        });

        studyBtn.setBackground(new java.awt.Color(229, 238, 255));
        studyBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        studyBtn.setForeground(new java.awt.Color(0, 55, 158));
        studyBtn.setText("Study");
        studyBtn.setBorder(null);
        studyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyBtnActionPerformed(evt);
            }
        });

        profileIcon.setBackground(new java.awt.Color(255, 255, 204));
        profileIcon.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        profileIcon.setForeground(new java.awt.Color(0, 55, 158));
        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa profile.png"))); // NOI18N
        profileIcon.setBorder(null);
        profileIcon.setBorderPainted(false);
        profileIcon.setContentAreaFilled(false);
        profileIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileIconActionPerformed(evt);
            }
        });

        flashcardsIcon.setBackground(new java.awt.Color(255, 255, 204));
        flashcardsIcon.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        flashcardsIcon.setForeground(new java.awt.Color(0, 55, 158));
        flashcardsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa flashcards.png"))); // NOI18N
        flashcardsIcon.setBorder(null);
        flashcardsIcon.setBorderPainted(false);
        flashcardsIcon.setContentAreaFilled(false);
        flashcardsIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flashcardsIconActionPerformed(evt);
            }
        });

        overviewIcon.setBackground(new java.awt.Color(255, 255, 204));
        overviewIcon.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        overviewIcon.setForeground(new java.awt.Color(0, 55, 158));
        overviewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeIcon.png"))); // NOI18N
        overviewIcon.setBorder(null);
        overviewIcon.setBorderPainted(false);
        overviewIcon.setContentAreaFilled(false);
        overviewIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewIconActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 55, 158));

        profileBtn.setBackground(new java.awt.Color(229, 238, 255));
        profileBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(0, 55, 158));
        profileBtn.setText("Profile");
        profileBtn.setBorder(null);
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        logOutIcon.setBackground(new java.awt.Color(255, 255, 204));
        logOutIcon.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        logOutIcon.setForeground(new java.awt.Color(0, 55, 158));
        logOutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa log out button.png"))); // NOI18N
        logOutIcon.setBorder(null);
        logOutIcon.setBorderPainted(false);
        logOutIcon.setContentAreaFilled(false);
        logOutIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutIconActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(229, 238, 255));
        logOutBtn.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(0, 55, 158));
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        flashcardsIcon1.setBackground(new java.awt.Color(255, 255, 204));
        flashcardsIcon1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        flashcardsIcon1.setForeground(new java.awt.Color(0, 55, 158));
        flashcardsIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studyIcon.png"))); // NOI18N
        flashcardsIcon1.setBorder(null);
        flashcardsIcon1.setBorderPainted(false);
        flashcardsIcon1.setContentAreaFilled(false);
        flashcardsIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flashcardsIcon1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(flashcardsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(profileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(logOutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(flashcardsIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(overviewIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(flashcardsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                        .addComponent(overviewBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(studyBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)))
                .addGap(30, 30, 30))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flashcardsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flashcardsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flashcardsIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOutIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        numCardsPanel.setBackground(new java.awt.Color(255, 255, 255));

        setOfCardsLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        setOfCardsLabel.setForeground(new java.awt.Color(0, 55, 158));
        setOfCardsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setOfCardsLabel.setText("Set of Cards");

        displayNumSets1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        displayNumSets1.setForeground(new java.awt.Color(0, 55, 158));
        displayNumSets1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        displayNumSets1.setBorder(null);
        displayNumSets1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayNumSets1ActionPerformed(evt);
            }
        });

        setIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa set.png"))); // NOI18N

        javax.swing.GroupLayout numCardsPanelLayout = new javax.swing.GroupLayout(numCardsPanel);
        numCardsPanel.setLayout(numCardsPanelLayout);
        numCardsPanelLayout.setHorizontalGroup(
            numCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numCardsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(numCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayNumSets1)
                    .addComponent(setOfCardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        numCardsPanelLayout.setVerticalGroup(
            numCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numCardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(numCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numCardsPanelLayout.createSequentialGroup()
                        .addComponent(displayNumSets1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setOfCardsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(setIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        headerOverviewPanel.setBackground(new java.awt.Color(255, 255, 204));
        headerOverviewPanel.setForeground(new java.awt.Color(0, 55, 158));

        displayUsername.setBackground(new java.awt.Color(255, 255, 204));
        displayUsername.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        displayUsername.setForeground(new java.awt.Color(0, 55, 158));
        displayUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        displayUsername.setBorder(null);
        displayUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayUsernameActionPerformed(evt);
            }
        });

        displayStatus.setBackground(new java.awt.Color(255, 255, 204));
        displayStatus.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        displayStatus.setForeground(new java.awt.Color(0, 55, 158));
        displayStatus.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        displayStatus.setText("Beginner");
        displayStatus.setBorder(null);
        displayStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayStatusActionPerformed(evt);
            }
        });

        headerprofileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa real pfp.png"))); // NOI18N

        javax.swing.GroupLayout headerOverviewPanelLayout = new javax.swing.GroupLayout(headerOverviewPanel);
        headerOverviewPanel.setLayout(headerOverviewPanelLayout);
        headerOverviewPanelLayout.setHorizontalGroup(
            headerOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerOverviewPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(headerprofileIcon)
                .addGap(18, 18, 18)
                .addGroup(headerOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .addComponent(displayStatus))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        headerOverviewPanelLayout.setVerticalGroup(
            headerOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerOverviewPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(headerOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerprofileIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addGroup(headerOverviewPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(displayStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(displayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        starIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaa single star.png"))); // NOI18N

        displayDayStreak.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        displayDayStreak.setForeground(new java.awt.Color(0, 55, 158));
        displayDayStreak.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        displayDayStreak.setBorder(null);
        displayDayStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDayStreakActionPerformed(evt);
            }
        });

        dayStreakLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        dayStreakLabel.setForeground(new java.awt.Color(0, 55, 158));
        dayStreakLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dayStreakLabel.setText("Day Streak");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(starIcon)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayStreakLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addComponent(displayDayStreak))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(starIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(displayDayStreak, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dayStreakLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator2.setForeground(new java.awt.Color(0, 55, 158));

        jSeparator4.setForeground(new java.awt.Color(0, 55, 158));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(numCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerOverviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidebarPanel.getAccessibleContext().setAccessibleName("sideBar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backgroundPanel.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void displayNumberOfSets() {
    // Define the user's folder path
    String userFolderPath = "C:\\Users\\Justin\\Documents\\NetBeansProjects\\Ussemble\\Flashcards\\" + Login.currentUsername;
    File userFolder = new File(userFolderPath);

    // Check if the folder exists
    if (userFolder.exists() && userFolder.isDirectory()) {
        // List all files in the folder and filter for .txt files
        File[] txtFiles = userFolder.listFiles((dir, name) -> name.toLowerCase().endsWith(".txt"));

        // Count the .txt files and display the number
        int numSets = txtFiles != null ? txtFiles.length : 0;
        displayNumSets1.setText(String.valueOf(numSets)); // Set the count in the JTextField
    } else {
        // If the folder doesn't exist, set the count to 0
        displayNumSets1.setText("0");
        System.out.println("User folder does not exist: " + userFolderPath);
    }
}

    
 public void setDisplayUsername(String username) {
    displayUsername.setText(username);
}
 
 public String getDisplayUsername() {
    return displayUsername.getText();
}

 public void setDisplayDayStreak(String streak) {
    displayDayStreak.setText(streak);
}
 

    private void overviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overviewBtnActionPerformed

    private void flashcardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flashcardsBtnActionPerformed
        // TODO add your handling code here:
        FlashcardsPage flashcard = new FlashcardsPage();
        flashcard.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_flashcardsBtnActionPerformed

    private void studyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyBtnActionPerformed
        // TODO add your handling code here:
        studySetPage study = new studySetPage();
        study.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_studyBtnActionPerformed

    private void profileIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileIconActionPerformed

    private void flashcardsIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flashcardsIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flashcardsIconActionPerformed

    private void overviewIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overviewIconActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        ProfilePage profile = new ProfilePage();
        profile.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_profileBtnActionPerformed

    private void logOutIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutIconActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // Show a confirmation dialog
    int choice = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Confirm LogOut?", 
        "Log Out", 
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        // Redirect to the login page
        Login loginPage = new Login();
        loginPage.setVisible(true);
        this.dispose(); // Close the current window
    } else {
        // Do nothing; close the dialog automatically
        System.out.println("Log out canceled.");
    }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void flashcardsIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flashcardsIcon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flashcardsIcon1ActionPerformed

    private void displayStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayStatusActionPerformed

    private void displayUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayUsernameActionPerformed

    private void displayNumSets1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayNumSets1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayNumSets1ActionPerformed

    private void displayDayStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDayStreakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayDayStreakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverviewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverviewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverviewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverviewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverviewPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel dayStreakLabel;
    public javax.swing.JTextField displayDayStreak;
    private javax.swing.JTextField displayNumSets1;
    private javax.swing.JTextField displayStatus;
    public static javax.swing.JTextField displayUsername;
    private javax.swing.JButton flashcardsBtn;
    private javax.swing.JButton flashcardsIcon;
    private javax.swing.JButton flashcardsIcon1;
    private javax.swing.JPanel headerOverviewPanel;
    private javax.swing.JLabel headerprofileIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton logOutIcon;
    private javax.swing.JPanel numCardsPanel;
    private javax.swing.JButton overviewBtn;
    private javax.swing.JButton overviewIcon;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton profileIcon;
    private javax.swing.JLabel setIcon;
    private javax.swing.JLabel setOfCardsLabel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel starIcon;
    private javax.swing.JButton studyBtn;
    // End of variables declaration//GEN-END:variables

   
}
